-- PVP/PVE mixed area zones
CREATE TABLE IF NOT EXISTS T_PvpArea_v1(
	Id TEXT NOT NULL PRIMARY KEY,
	CreatedAt TEXT NOT NULL,
	AreaNote TEXT NOT NULL,
	X1 INTEGER NOT NULL,
	Z1 INTEGER NOT NULL,
	X2 INTEGER NOT NULL,
	Z2 INTEGER NOT NULL,
	AreaNoticeBuff TEXT NOT NULL,
	KillMode TEXT NOT NULL,
	DropOnDeath TEXT NOT NULL,
	OnlineLandClaimBonus INTEGER NOT NULL,
	OfflineLandClaimBonus INTEGER NOT NULL,
	InvulnerableClaim INTEGER NOT NULL,
	SortOrder INTEGER NOT NULL
);
