-- Lottery pools
CREATE TABLE IF NOT EXISTS T_LotteryPool_v1(
	Id INTEGER NOT NULL PRIMARY KEY,
	CreatedAt TEXT NOT NULL,
	Name TEXT NOT NULL,
	DrawCost INTEGER NOT NULL,
	Weight INTEGER NOT NULL,
	IsEnabled INTEGER NOT NULL,
	Description TEXT
);

PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE IF NOT EXISTS T_LotteryPoolItem(
	LotteryPoolId INTEGER NOT NULL,
	ItemId INTEGER NOT NULL,
	PRIMARY KEY (LotteryPoolId, ItemId),
	FOREIGN KEY (LotteryPoolId) REFERENCES T_LotteryPool_v1(Id) ON DELETE CASCADE,
	FOREIGN KEY (ItemId) REFERENCES T_ItemList(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS T_LotteryPoolCommand(
	LotteryPoolId INTEGER NOT NULL,
	CommandId INTEGER NOT NULL,
	PRIMARY KEY (LotteryPoolId, CommandId),
	FOREIGN KEY (LotteryPoolId) REFERENCES T_LotteryPool_v1(Id) ON DELETE CASCADE,
	FOREIGN KEY (CommandId) REFERENCES T_CommandList(Id) ON DELETE CASCADE
);
